version: 1
formatters:
  simple:
    format: '[%(asctime)s][%(name)s][%(levelname)s] - %(message)s'
handlers:
  console:
    level: INFO
    class: logging.StreamHandler
    formatter: simple
    stream: ext://sys.stdout
  file:
    level: DEBUG
    class: logging.FileHandler
    formatter: simple
    filename: componentSMZU.log
root:
  level: DEBUG
  handlers: [console, file]

disable_existing_loggers: false
